### ISSUE TITLE
Repo deletion?

### ISSUE THREAD

**Issue by zauster** [abresler/gdeltr2#1]
Did you delete your repo? Looks different now...

**Comment by abresler** [comment]
Yes

**Comment by zauster** [comment]
can i ask why?

**Comment by abresler** [comment]
Because there was an issue with the git and it is a giant pain in the ass
to rollback and debug it


----------------------
Alex Bresler
abresler@asbcllc.com

​www.asbcllc.com​

917-455-0239 (cell)
