### ISSUE TITLE
Incorrect README.md

### ISSUE THREAD

**Issue by erzk** [abresler/gdeltr2#10]
Hi Alex,
Thanks for the gdeltr2 package. It's super useful.

I've noticed that your README file is mentioning functions that do not exist in the latest version of the package:
In **Primary functions/Full text API**:
```
get_data_ft_api_domains()
get_data_ft_api_terms() 

```

I'm not sure whether you were planning to add these functions or were they removed so I'm not submitting a PR.

**Comment by MarcinKosinski** [comment]
@abresler +1 for the @erzk comment

**Comment by abresler** [comment]
Depricated functions

**Comment by MarcinKosinski** [comment]
@abresler I can provide the PR with the cut-ed readme then, so there is no confusion for future users
