### ISSUE TITLE
Packages missing in DESCRIPTION Imports

### ISSUE THREAD

**Issue by erzk** [abresler/gdeltr2#11]
I've noticed that `gdelt_full_text_api()` is calling plotly and hrbrthemes, but none of these packages are specified in the DESCRIPTION file. It might be worth adding them to the list.

**Comment by MarcinKosinski** [comment]
+1 for @erzk good catch - `plotly` and `hrbrthemes` are in NAMESPACE but not in the DESCRIPTION
PR here https://github.com/abresler/gdeltr2/pull/12 @abresler

**Comment by abresler** [comment]
Those functions that use those libraries are no longer in the package

**Comment by MarcinKosinski** [comment]
Well, so it'll be perfect to remove them from the NAMEPSACE and the roxygenized @import tag
