### ISSUE TITLE
Package asbviz missing

### ISSUE THREAD

**Issue by quantsulting** [abresler/gdeltr2#14]
Hi you posted a few examples using the gdeltr2 package as the one below. Unfortunately I'm not able to find the function asbviz::hc_xy you use. Is this package still available ?

gdeltr2::ft_v2_api(
  terms = c("RepRisk", "Sentify", "Thomas", "Aebi"),
  modes = c("TimelineVolInfo"),
  visualize_results = F,
  timespans = "13 days",
  source_countries = "US"
) %>%
  rename(tone = value) %>%
  asbviz::hc_xy(
    name = "titleArticle",
    x = "datetimeData",
    y = "tone",
    group = "termSearch",
    title = "Media Tone -- Last 13 Days",
    subtitle = "data via gdeltr2",
    type = "spline",
    link = "urlArticle",
    use_point_select = T,
    color_palette = "pals::kovesi.rainbow_bgyr_35_85_c73",
    override_legend_location = NULL,
    theme_name = "elementary",
  )

**Comment by abresler** [comment]
Sorry asbviz is not a public package.

You can try visualizing using highcharter or ggplot2
