### ISSUE TITLE
hide readr messages with suppressMessages

### ISSUE THREAD

**Issue by MarcinKosinski** [abresler/gdeltr2#18]
like here

```{R}
suppressMessages(read_csv(readr_example("mtcars.csv")) -> x)
```

this is just the proposition

**Comment by abresler** [comment]
I know how to use this function but I am not suppressing messages here

**Comment by MarcinKosinski** [comment]
what about making this an extra parameter `suppress = FALSE` as a default and then make this be a feature that a user can benefit from?
