### ISSUE TITLE
Several functions not found in 0.1.1

### ISSUE THREAD

**Issue by pssguy** [abresler/gdeltr2#2]
eg

Error: could not find function "get_data_gdelt_period_event"
Error: could not find function "get_data_gkg_tv_day"
Error: could not find function "get_data_sentiment_ft_api"

**Comment by abresler** [comment]
Those are not functions that are exposed to people in the package; you should try reinstalling.

If you want to use those functions the functions below expose the functions.

```
gdeltr2::get_data_gkg_tv_days()
gdeltr2::get_data_gdelt_period_event()
gdeltr2::get_data_sentiment_ft_api_terms()

```
