### ISSUE TITLE
Other GDELT resources

### ISSUE THREAD

**Issue by geotheory** [abresler/gdeltr2#2]
Nice project - I'll be testing this out. Any plans to harness the other BigQuery based resources including [Entity Graph](https://blog.gdeltproject.org/announcing-the-global-entity-graph-geg-and-a-new-11-billion-entity-dataset/) and [Frontpage Graph](https://blog.gdeltproject.org/announcing-gdelt-global-frontpage-graph-gfg/)?

**Comment by abresler** [comment]
Front page is included but bigquery wont be
