### ISSUE TITLE
get_data_ft_v2_api() stopped working

### ISSUE THREAD

**Issue by brendankness** [abresler/gdeltr2#20]
Every combination of args causes this:
````
Error in mutate_impl(.data, dots) : 
  Evaluation error: object 'modeSearch' not found.
In addition: Warning message:
Unknown variables: `isOR`, `countMaximumRecords` 
````

I have rerun scripts where I've used before and they are now throwing this error as well. Lots of tidyverse updates as of late may be a dependency change.

**Comment by abresler** [comment]
GDELT full text API is down for now will be back up tomorrow if you are looking at a narrow timespan. It still works on a longer time span.

```
get_data_ft_v2_api(terms = "Brooklyn Nets", timespans = "12 days")
```
