### ISSUE TITLE
issue with modes in function get_data_ft_v2_api()

### ISSUE THREAD

**Issue by mrosenast** [abresler/gdeltr2#25]
Hi all,
When trying to run get_data_ft_v2_api(terms = c("Wasserstoff", "Auto"), timespans = "12 days", modes = c("TimelineTone"), visualize_results = TRUE) the following error appears: Error in eval(lhs, parent, parent) : object 'modeSearch' not found
In addition: Warning message:
Unknown columns: `isOR`, `countMaximumRecords`
When looking at the raw data file of my request (visualize_results = FALSE), I recognized that the dataframe is empty, consequently no column "Tone" is available. How does the code need to be adapted in order to get the "TimelineTone" or other sentiment related modes such as "ToneChart"? Many thanks for any suggestions.

**Comment by abresler** [comment]
It isn't working because there are no results for your search
