### ISSUE TITLE
Specify range of dates for periods

### ISSUE THREAD

**Issue by mayeulk** [abresler/gdeltr2#26]
If dates are used, only data for the first and last day are downloaded.

```
x<-get_data_gdelt_periods_event(periods = c(20190428,20190501),
                             file_directory = NULL, folder_name = "gdelt_data",
                             remove_files = T, empty_trash = T, return_message = T)
Downloaded, parsed and imported http://data.gdeltproject.org/events/20190428.export.CSV.zip
You retrieved 100781 GDELT events for the period of 20190428
Downloaded, parsed and imported http://data.gdeltproject.org/events/20190501.export.CSV.zip
You retrieved 191570 GDELT events for the period of 20190501
```
Expected result: download days between first and last date

**Comment by mayeulk** [comment]
As a workaround, I am using this:

`dates_to_download <- seq.Date (from = as.Date.character("2019-04-28"), to=as.Date.character("2019-05-01"), by=1) %>% str_replace_all('\\-', '') %>% as.numeric()
`
Then:
`x<-get_data_gdelt_periods_event(periods = dates_to_download, ...)`
Tests should handle the fact that some datasets are available in the following pattern:
Periods are by 4 digit years from 1979 to 2005, 6 digit year month from January 2006 to March 2013, and 8 digit year month day code thereafter.
I'd be happy to code a helper function that would expand any range of date into a vector of integers compatible with the above specifications, if that helps.

**Comment by abresler** [comment]
There is already a function in the package that does this but thank you

http://asbcllc.com/gdeltr2/reference/generate_dates.html
