### ISSUE TITLE
Download 3 montly daily trend for keywords?

### ISSUE THREAD

**Issue by MarkEdmondson1234** [abresler/gdeltr2#4]
Is it possible to do say a trend for longer than 24 hours with `get_data_ft_api_terms(` without needing to download everything?  Or should I look at daily downloading using the above?

I'm thinking about a brand monitoring function which 24 hours isn't long enough to be useful.

**Comment by abresler** [comment]
No the API only works for 24 hour periods.  

You can use the actual GKG files to search for your specified terms or the best thing to do is to setup a chmod script to run every day with your specified terms and save them into a database.
