### ISSUE TITLE
gdeltr2 functions access gdelt v1 vars, not v2 vars

### ISSUE THREAD

**Issue by profkenm** [abresler/gdeltr2#5]
GDELT 2.0 variables are mentioned in several places of the gdeltr2 documentation, but unless I am missing something, none of the v2 variables, that have been added in the past few years, are accessible using gdeltr2.  I have used these gdeltr2 functions to access gdelt data, but they return only v1 variables, not v2 variables.

This is true for these gdeltr2 functions:
 
gkg_tv_days()
get_data_gkg_days_detailed()
ft_v2_api()

Would it be possible to update gdeltr2 so that it can access the full v2 api?  As you know, it includes these variables from the codebook.

http://data.gdeltproject.org/documentation/GDELT-Global_Knowledge_Graph_Codebook-V2.pdf

Thank you for gdeltr2

Ken

**Comment by abresler** [comment]
It's best to use big query for this which is not included in the package


----------------------
Alex Bresler
abresler@asbcllc.com

​www.asbcllc.com​

917-455-0239 (cell)

**Comment by abresler** [comment]
Best to use gdelt access from bigquery for this which is outside of the scope of this package
