### ISSUE TITLE
readr parse_number

### ISSUE THREAD

**Issue by fredheir** [abresler/gdeltr2#7]
Hi Alex,

Thanks for a cracking package!
The GKG and mentions wrapper functions are throwing an error:

Error in .::readr : unused argument (parse_number)

I'm getting this in Ubuntu 16.04, with R 3.3.2, and latest devtools versions of devtools, dplyr, tidyverse, and readr
For some reason I'm not getting proper tracebacks so can't say much more, other than to paste the start of the error below.

-Rolf

> gkg_summary_count_may_15_16_2014 <-
+   get_data_gkg_days_summary(
+     dates = c('2014-05-15', '2014-05-16'),
+     is_count_file = T,
+     return_message = T
+   )
To save time and memory next time you should run the function get_urls_gkg_daily_summaries and save it to a data frame called summary_data_urls
Parsed with column specification:
cols(
  X1 = col_character()
)
You got 2716 GDELT Global Knowledge Graph URLS from 2013-04-01 to 2016-12-21
Parsed with column specification:
cols(
  X1 = col_character(),
  X2 = col_character(),
  X3 = col_character(),
  X4 = col_character(),
  X5 = col_character(),
  X6 = col_character(),
  X7 = col_character(),
  X8 = col_character(),
  X9 = col_character(),
  X10 = col_character(),
  X11 = col_character(),
  X12 = col_character(),
  X13 = col_character(),
  X14 = col_character(),
  X15 = col_character()
)
Error in .::readr : unused argument (parse_number)
You retrieved 0 gkg summary events for 2014-05-15

**Comment by abresler** [comment]
Will take a look!

**Comment by abresler** [comment]
Reinstall the most recent push you should get:

```
> gkg_summary_count_may_15_16_2014 <-
+   get_data_gkg_days_summary(
+     dates = c('2014-05-15', '2014-05-16'),
+     is_count_file = T,
+     return_message = T
+   )
You got 2718 GDELT Global Knowledge Graph URLS from 2013-04-01 to 2016-12-22
Downloaded, parsed and imported http://data.gdeltproject.org/gkg/20140515.gkgcounts.csv.zip
You retrieved 11202 gkg summary events for 2014-05-15
Downloaded, parsed and imported http://data.gdeltproject.org/gkg/20140516.gkgcounts.csv.zip
You retrieved 9782 gkg summary events for 2014-05-16

```

Within the next few weeks there should be a more major update but let me know if there are still issues.

**Comment by fredheir** [comment]
Sorry for the slow reply - holidays and what not got in the way.
But - I've reinstalled the latest push and everything seems to be working beautifully.
